@echo off
cd %cd%\adb
adb shell pm uninstall --user 0 com.huawei.browser
adb shell pm uninstall --user 0 com.huawei.browserhomepage
adb shell pm uninstall --user 0 com.android.bookmarkprovider
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.huawei.wallet
adb shell pm uninstall --user 0 com.huawei.wallet.sdk.walletsdk
adb shell pm uninstall --user 0 com.huawei.music
adb shell pm uninstall --user 0 com.huawei.hifolder
adb shell pm uninstall --user 0 com.huawei.hitouch
adb shell pm uninstall --user 0 com.huawei.fastapp
adb shell pm uninstall --user 0 com.huawei.magazine
adb shell pm uninstall --user 0 com.huawei.hwpanpayservice
adb shell pm uninstall --user 0 com.bjbyhd.screenreader_huawei
adb shell pm uninstall --user 0 com.huawei.android.karaoke
adb shell pm uninstall --user 0 com.huawei.himovie.overseas
adb shell pm uninstall --user 0 com.huawei.hwsearch
adb shell pm uninstall --user 0 com.huawei.hwvoipservice
adb shell pm uninstall --user 0 com.hicloud.android.clone
adb shell pm uninstall --user 0 com.huawei.android.chr
adb shell pm uninstall --user 0 com.huawei.bluetooth
adb shell pm uninstall --user 0 com.huawei.tips
adb shell pm uninstall --user 0 com.huawei.contactscamcard
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 com.huawei.android.instantshare
adb shell pm uninstall --user 0 com.huawei.nearby
adb shell pm uninstall --user 0 com.huawei.photos
adb shell pm uninstall --user 0 com.touchtype.swiftkey
adb shell pm uninstall --user 0 com.swiftkey.swiftkeyconfigurator
adb shell pm uninstall --user 0 com.huawei.phoneservice
adb shell pm uninstall --user 0 com.huawei.parentcontrol
adb shell pm uninstall --user 0 com.huawei.hiassistantoversea
adb shell pm uninstall --user 0 com.huawei.imedia.sws
adb shell pm uninstall --user 0 com.huawei.intelligent
adb shell pm uninstall --user 0 com.huawei.hwstartupguide
adb shell pm uninstall --user 0 com.android.onetimeinitializer
adb shell pm uninstall --user 0 com.huawei.search
adb shell pm uninstall --user 0 com.huawei.hwdetectrepair
adb shell pm uninstall --user 0 com.huawei.hiview
adb shell pm uninstall --user 0 com.huawei.hiviewtunnel
adb shell pm uninstall --user 0 com.huawei.featurelayer.sharedfeature.map
adb shell pm uninstall --user 0 com.hisi.mapcon
adb shell pm uninstall --user 0 com.android.stk
adb shell pm uninstall --user 0 com.huawei.scanner
adb shell pm uninstall --user 0 com.huawei.mirror
adb shell pm uninstall --user 0 com.huawei.android.wfdft
adb shell pm uninstall --user 0 com.huawei.android.wfdirect
adb shell pm uninstall --user 0 com.huawei.trustagent
adb shell pm uninstall --user 0 com.huawei.fido.uafclient
adb shell pm uninstall --user 0 com.huawei.hwasm
adb shell pm uninstall --user 0 com.huawei.synergy
adb shell pm uninstall --user 0 com.huawei.notepad
adb shell pm uninstall --user 0 com.huawei.rcsserviceapplication
adb shell pm uninstall --user 0 com.huawei.health
adb shell pm uninstall --user 0 com.huawei.email
adb shell pm uninstall --user 0 com.huawei.livewallpaper.paradise
adb shell pm uninstall --user 0 com.huawei.android.instantonline
adb shell pm uninstall --user 0 com.huawei.hwblockchain
adb shell pm uninstall --user 0 com.huawei.hiaction
adb shell pm uninstall --user 0 com.huawei.hicard
adb shell pm uninstall --user 0 com.huawei.hff
adb shell pm uninstall --user 0 com.huawei.def
adb shell pm uninstall --user 0 com.huawei.hwddmp
adb shell pm uninstall --user 0 com.huawei.dmsdp
adb shell pm uninstall --user 0 com.huawei.nb.service
adb shell pm uninstall --user 0 com.huawei.searchservice
adb shell pm uninstall --user 0 com.huawei.frameworkhwext.honor
adb shell pm uninstall --user 0 com.huawei.iconnect
adb shell pm uninstall --user 0 com.huawei.hicloud
adb shell pm uninstall --user 0 com.huawei.hidisk
adb shell pm uninstall --user 0 com.huawei.powergenie
adb shell pm uninstall --user 0 com.huawei.ims
cls
